### ISSUE TITLE
Progress spinner should be disabled in CI mode

### ISSUE THREAD

**Issue by mickeyreiss-visor** [0x80/yurnalist#7]
Seeing rather ugly output when I build my gatsby app in Circle CI.

![image](https://user-images.githubusercontent.com/30812527/32795288-19f92d2e-c920-11e7-885b-262b203d8ca9.png)

I see that the library already supports CI for other pieces, so I was hoping it would be easy to disable the spinner as well in CI, and instead just output a new line of text for each status update.

cc/ @KyleAMathews

**Comment by 0x80** [comment]
Hi @mickeyreiss-visor I've just updated yurnalist to use the code from the yarn master branch (1.13.0).

I noticed that there was a new `YARN_SILENT` env variable that could be set to disable the output. I've copied that behavior, but only using `YURNALIST_SILENT`. If you set this in your CI config I guess things are muted at the output. 

Let me know if this doesn't cut it.

**Comment by 0x80** [comment]
@mickeyreiss-visor 	there was a problem with the published built files and I can't figure it out yet. I unpublished the release for now and will look at it another time.

**Comment by 0x80** [comment]
I blindly copied the npmignore contents from the yarn repo which included the dist folder since yarn uses a different approach to publishing new versions. This messed up the module on publish. 

I could not re-publish 1.0.0 because it was already un-published (as was 1.0.1), so the latest version is now 1.0.2.

**Comment by markmssd** [comment]
I'm seeing the same issue running on NodeJS 10 (it wasn't happening on v8). The pre-installed `yarn` versions are:

NodeJS 10: Yarn v1.16
NodeJS 8: Yarn v1.15.2

Is it possible that something changed again between those versions?

**Comment by 0x80** [comment]
@markmssd 	I have no idea. I would not expect Yurnalist's behavior to change depending on Node or Yarn versions. I will try to reserve some time in the near future to do some tests and solve this issue.

**Comment by markmssd** [comment]
Hey :) Did you figure out something? I haven't on my side so far. :(

**Comment by 0x80** [comment]
@markmssd No sorry. With "near future" I wasn't thinking about 4 days ;)

**Comment by 0x80** [comment]
I looked into the issue. Silent mode affects `info` and some other console output but not `activity` or `progress`.

The activity and progress functions were blocked by the isTTY check, and I would expect that to be false for CI environments.

In order to solve this issue I have done two things:

* Make silent mode affect activity and progress output, so you YURNALIST_SILENT will have effect on those outputs.
* Add an isCI check to automatically disable activity and progress output on CI environments.

See https://github.com/0x80/yurnalist/pull/20

**Comment by 0x80** [comment]
I've released version [2.0.0](https://github.com/0x80/yurnalist/releases/tag/v2.0.0) with the changes

**Comment by markmssd** [comment]
This is awesome, thanks @0x80 🎉
